@host = http://localhost:5112

GET {{host}}/admin/import-stations

###

GET {{host}}/stations?route=Red

###

GET {{host}}/stations/nearest?lat=42.3564&lon=-71.0624&route=Red

###

GET {{host}}/stations/place-pktrm

###

GET {{host}}/stations/place-pktrm/predictions?route=Red&direction=0
